Repository porcupine7021/Solebid, pull requests merged in 2025-09, with the labels that each got.

#156 chore: Install echarts
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙️chore

#159 chore: Uninstall echarts
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙️chore

#160 feat: Redis 기반 OAuth2 State 서비스 및 설정 구현
  backend/demo/.gitignore
  backend/demo/build.gradle
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/service/InMemoryOAuth2StateService.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2StateService.java
  backend/demo/src/main/java/com/sesac/solbid/service/RedisOAuth2StateService.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2StateServiceTest.java
Labels: ✨feat

#162 chore: Install react markdown
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙️chore

#164 feat: Apply rounded corners to components
  frontend/src/features/main/components/MainContent.tsx
  frontend/src/features/main/components/mockData.ts
  frontend/src/features/product/components/auction/AuctionItem.tsx
  frontend/src/features/product/components/auction/AuctionList.tsx
  frontend/src/features/product/components/auction/AuctionSearch.tsx
  frontend/src/features/product/components/search/SearchHeader.tsx
  frontend/src/features/product/components/search/SearchSidebar.tsx
  frontend/src/features/setting/components/SettingAccount.tsx
Labels: ✨feat

#174 refactor: Consolidate Main page
  frontend/src/components/AppHeader.tsx
  frontend/src/features/main/components/MainBrand.tsx
  frontend/src/features/main/components/MainCategory.tsx
  frontend/src/features/main/components/MainCategoryList.tsx
  frontend/src/features/main/components/MainContent.tsx
  frontend/src/features/main/components/MainHeroSection.tsx
  frontend/src/features/main/components/MainProduct.tsx
  frontend/src/features/main/components/MainProductList.tsx
  frontend/src/features/main/components/index.ts
  frontend/src/features/main/components/mockData.ts
  frontend/src/features/main/pages/MainPage.tsx
  frontend/src/features/main/types/.gitkeep
  frontend/src/features/main/types/MainBrandProps.ts
  frontend/src/features/main/types/MainCategoryListProps.ts
  frontend/src/features/main/types/MainCategoryProps.ts
  frontend/src/features/main/types/MainHeroSectionProps.ts
  frontend/src/features/main/types/MainProductListProps.ts
  frontend/src/features/main/types/MainProductProps.ts
  frontend/src/features/product/components/brand/BrandItem.tsx
  frontend/src/features/product/components/brand/BrandList.tsx
  frontend/src/features/product/components/brand/BrandModal.tsx
  frontend/src/features/product/components/brand/index.ts
  frontend/src/features/product/components/brand/mockData.ts
  frontend/src/features/product/pages/BrandPage.tsx
  frontend/src/features/product/types/brand/Brand.ts
  frontend/src/features/product/types/brand/BrandItemProps.ts
  frontend/src/features/product/types/brand/BrandListProps.ts
  frontend/src/features/product/types/brand/BrandModalProps.ts
  frontend/src/features/product/types/brand/BrandPopular.ts
  frontend/src/router.tsx
Labels: 🍀refactor

#176 feat: get payment records
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentRecordQueryController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/request/PaymentRecordSearchRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/response/PageResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/response/PaymentRecordItemResponse.java
  backend/demo/src/main/java/com/sesac/solbid/repository/PaymentsRepository.java
  backend/demo/src/main/java/com/sesac/solbid/repository/spec/PaymentsSpecs.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentRecordQueryService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentRecordQueryServiceImpl.java
Labels: ✨feat

#177 feat: Add disabled styles to buttons
  frontend/src/components/Pagination.tsx
Labels: ✨feat

#187 fix: Resolve category filter
  frontend/src/features/product/components/category/mockData.ts
  frontend/src/features/product/pages/CategoryPage.tsx
  frontend/src/features/product/types/category/Category.ts
Labels: 🌈fix

#189 feat: 공통 fetch 래퍼, 인증 시스템 구현 및 사용 가이드 추가
  frontend/docs/AUTH_GUIDE.md
  frontend/src/features/profile/api/point.ts
  frontend/src/features/profile/components/ProfilePoint.tsx
  frontend/src/features/user/components/ProtectedRoute.tsx
  frontend/src/features/user/hooks/useAuth.ts
  frontend/src/router.tsx
  frontend/src/utils/apiFetch.ts
Labels: ✨feat

#191 refactor: Update Search page
  frontend/src/components/AppHeader.tsx
  frontend/src/features/product/components/search/SearchHeader.tsx
  frontend/src/features/product/components/search/SearchItem.tsx
  frontend/src/features/product/components/search/SearchSidebar.tsx
  frontend/src/features/product/components/search/index.ts
  frontend/src/features/product/components/search/mockData.ts
  frontend/src/features/product/pages/SearchPage.tsx
  frontend/src/features/search/components/SearchHeader.tsx
  frontend/src/features/search/components/SearchHistory.tsx
  frontend/src/features/search/components/SearchProduct.tsx
  frontend/src/features/search/components/SearchRankingItem.tsx
  frontend/src/features/search/components/SearchRankingList.tsx
  frontend/src/features/search/components/index.ts
  frontend/src/features/search/components/mockData.ts
  frontend/src/features/search/pages/SearchPage.tsx
  frontend/src/features/search/types/SearchHeaderProps.ts
  frontend/src/features/search/types/SearchHistoryProps.ts
  frontend/src/features/search/types/SearchModalProps.ts
  frontend/src/features/search/types/SearchProductProps.ts
  frontend/src/features/search/types/SearchRankingProps.ts
  frontend/src/router.tsx
Labels: 🍀refactor

#193 refactor: Remove unnecessary component
  frontend/src/features/product/components/ranking/RankingBidderItem.tsx
  frontend/src/features/product/components/ranking/RankingBidderList.tsx
  frontend/src/features/product/components/ranking/RankingProductItem.tsx
  frontend/src/features/product/components/ranking/RankingProductList.tsx
  frontend/src/features/product/components/ranking/RankingSellerItem.tsx
  frontend/src/features/product/components/ranking/RankingSellerList.tsx
  frontend/src/features/product/components/ranking/RankingTab.tsx
  frontend/src/features/product/components/ranking/index.ts
  frontend/src/features/product/components/ranking/mockData.ts
  frontend/src/features/product/hooks/useClickOutside.ts
  frontend/src/features/product/pages/RankingPage.tsx
  frontend/src/features/product/types/ranking/RankingBidderProps.ts
  frontend/src/features/product/types/ranking/RankingProductProps.ts
  frontend/src/features/product/types/ranking/RankingSellerProps.ts
  frontend/src/features/product/types/ranking/RankingTabProps.ts
  frontend/src/features/product/types/search/Search.ts
  frontend/src/features/product/types/search/SearchHeaderProps.ts
  frontend/src/features/product/types/search/SearchItemProps.ts
  frontend/src/features/product/types/search/SearchSidebarProps.ts
  frontend/src/router.tsx
Labels: 🍀refactor

#199 feat: Add Transaction page
  frontend/src/features/profile/components/ProfileTransaction.tsx
  frontend/src/features/transaction/components/TransactionItem.tsx
  frontend/src/features/transaction/components/TransactionList.tsx
  frontend/src/features/transaction/components/TransactionSearch.tsx
  frontend/src/features/transaction/components/TransactionStatus.tsx
  frontend/src/features/transaction/components/TransactionSummary.tsx
  frontend/src/features/transaction/components/index.ts
  frontend/src/features/transaction/components/mockData.ts
  frontend/src/features/transaction/pages/TransactionPage.tsx
  frontend/src/features/transaction/types/Transaction.ts
  frontend/src/features/transaction/types/TransactionItemProps.ts
  frontend/src/features/transaction/types/TransactionListProps.ts
  frontend/src/features/transaction/types/TransactionSearchProps.ts
  frontend/src/features/transaction/types/TransactionStatusProps.ts
  frontend/src/features/transaction/types/TransactionSummaryProps.ts
  frontend/src/router.tsx
  frontend/src/utils/get-status-color.ts
Labels: ✨feat

#202 feat: 경매 로직 반영을 위한 엔티티 구조 개편
  backend/demo/src/main/java/com/sesac/solbid/domain/AuctionEvent.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Bid.java
  backend/demo/src/main/java/com/sesac/solbid/domain/PointTransaction.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Product.java
  backend/demo/src/main/java/com/sesac/solbid/domain/enums/AuctionStatus.java
Labels: ✨feat

#204 feat: Add Transaction detail page
  frontend/src/features/transaction/components/TransactionItem.tsx
  frontend/src/features/transaction/components/detail/TransactionDetailBuyer.tsx
  frontend/src/features/transaction/components/detail/TransactionDetailPayment.tsx
  frontend/src/features/transaction/components/detail/TransactionDetailProduct.tsx
  frontend/src/features/transaction/components/detail/TransactionDetailShipping.tsx
  frontend/src/features/transaction/components/index.ts
  frontend/src/features/transaction/components/mockData.ts
  frontend/src/features/transaction/pages/TransactionDetailPage.tsx
  frontend/src/features/transaction/pages/TransactionPage.tsx
  frontend/src/features/transaction/types/Transaction.ts
  frontend/src/features/transaction/types/TransactionBuyer.ts
  frontend/src/features/transaction/types/TransactionDetail.ts
  frontend/src/features/transaction/types/TransactionPayment.ts
  frontend/src/features/transaction/types/TransactionProduct.ts
  frontend/src/features/transaction/types/TransactionShipping.ts
  frontend/src/router.tsx
Labels: ✨feat

#211 feat: 경매 관련 엔티티 수정
  backend/demo/src/main/java/com/sesac/solbid/domain/AuctionEvent.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Bid.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Product.java
  backend/demo/src/main/java/com/sesac/solbid/domain/ProductImage.java
Labels: ✨feat

#213 feat: JWT 인증 필터 및 커스텀 사용자 정보 서비스 구현
  backend/demo/src/main/java/com/sesac/solbid/security/CustomUserDetailsService.java
  backend/demo/src/main/java/com/sesac/solbid/security/JwtAuthenticationFilter.java
  backend/demo/src/main/java/com/sesac/solbid/security/SecurityConfig.java
Labels: ✨feat

#214 feat: 상품 등록 API 구현
  backend/demo/build.gradle
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/AuctionEvent.java
  backend/demo/src/main/java/com/sesac/solbid/domain/ProductImage.java
  backend/demo/src/main/java/com/sesac/solbid/domain/enums/AuctionStatus.java
  backend/demo/src/main/java/com/sesac/solbid/dto/product/request/ProductCreateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/product/response/ProductCreateResponse.java
  backend/demo/src/main/java/com/sesac/solbid/exception/ErrorCode.java
  backend/demo/src/main/java/com/sesac/solbid/mapper/ProductImageMapper.java
  backend/demo/src/main/java/com/sesac/solbid/mapper/ProductMapper.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductService.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductServiceImpl.java
Labels: ✨feat

#217 fix: Resolved an issue with inconsistent font weights in the Pretendard font
  frontend/public/fonts/Pretendard-Bold.woff2
  frontend/public/fonts/Pretendard-Regular.woff
  frontend/public/fonts/Pretendard-SemiBold.woff2
  frontend/src/global.css
Labels: 🌈fix

#231 feat(frontend): Auction API integration
  frontend/src/features/auction/components/AuctionModal.tsx
  frontend/src/features/auction/pages/AuctionPage.tsx
  frontend/src/features/auction/services/AuctionService.tsx
  frontend/src/features/auction/types/AuctionItem.ts
  frontend/src/features/auction/types/AuctionModalProps.ts
  frontend/src/main.tsx
Labels: ✨feat

#234 chore: Install date fns
  frontend/package-lock.json
  frontend/package.json
Labels: ⚙️chore

#245 chore: Add .env file to .gitignore
  .gitignore
Labels: ⚙️chore

#252 refactor: Cleanup Auction page
  frontend/src/features/auction/components/mockData.ts
  frontend/src/features/auction/pages/AuctionPage.tsx
  frontend/src/features/auction/services/AuctionService.tsx
Labels: 🍀refactor

#257 feat(frontend): Main API integration
  frontend/src/features/auction/services/AuctionService.tsx
  frontend/src/features/main/hooks/useMainProducts.ts
Labels: ✨feat

#261 refactor(config): PasswordEncoder Bean을 별도 설정 파일로 분리
  backend/demo/src/main/java/com/sesac/solbid/config/PasswordConfig.java
  backend/demo/src/main/java/com/sesac/solbid/security/SecurityConfig.java
Labels: 🍀refactor

#262 feat: 회원가입 시 이메일 인증 기능 추가
  backend/demo/build.gradle
  backend/demo/src/main/java/com/sesac/solbid/DemoApplication.java
  backend/demo/src/main/java/com/sesac/solbid/controller/EmailVerificationController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/User.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/ResendVerificationRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/VerifyCodeRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/SignupResponse.java
  backend/demo/src/main/java/com/sesac/solbid/exception/EmailVerificationException.java
  backend/demo/src/main/java/com/sesac/solbid/exception/EmailVerificationExceptionUtils.java
  backend/demo/src/main/java/com/sesac/solbid/exception/ErrorCode.java
  backend/demo/src/main/java/com/sesac/solbid/exception/GlobalExceptionHandler.java
  backend/demo/src/main/java/com/sesac/solbid/security/JwtAuthenticationFilter.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/EmailService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/EmailVerificationService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/EmailVerificationTokenService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/InMemoryEmailVerificationTokenService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/PasswordResetService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/RedisEmailVerificationTokenService.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/UserService.java
  backend/demo/src/test/java/com/sesac/solbid/controller/EmailVerificationControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/exception/EmailVerificationExceptionTest.java
  backend/demo/src/test/java/com/sesac/solbid/exception/EmailVerificationExceptionUtilsTest.java
  backend/demo/src/test/java/com/sesac/solbid/exception/GlobalExceptionHandlerTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/EmailVerificationTokenServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/EmailServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/EmailVerificationServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/UserServiceSignupTest.java
  frontend/src/features/user/components/VerificationCodeInput.tsx
  frontend/src/features/user/hooks/UseEmailLogin.ts
  frontend/src/features/user/hooks/UseSignup.ts
  frontend/src/features/user/hooks/useEmailVerification.ts
  frontend/src/features/user/pages/EmailVerificationPage.tsx
  frontend/src/features/user/pages/EmailVerificationSuccess.tsx
  frontend/src/features/user/pages/Signup.tsx
  frontend/src/features/user/services/EmailVerificationService.ts
  frontend/src/features/user/types/EmailVerificationTypes.ts
  frontend/src/features/user/types/SignupTypes.ts
  frontend/src/router.tsx
Labels: ✨feat

#270 feat(frontend): Apply Presigned URL
  frontend/src/features/auction/components/AuctionItem.tsx
  frontend/src/features/auction/hooks/useAuctions.ts
  frontend/src/features/auction/pages/AuctionPage.tsx
  frontend/src/features/auction/types/AuctionItem.ts
  frontend/src/features/main/hooks/useMainProducts.ts
  frontend/src/features/main/pages/MainPage.tsx
  frontend/src/features/product/services/ProductService.ts
  frontend/src/features/search/pages/SearchPage.tsx
  frontend/src/features/wish/components/WishItem.tsx
  frontend/src/features/wish/hooks/useWishes.ts
  frontend/src/features/wish/types/Wish.ts
  frontend/src/hooks/useProductImageUrls.ts
Labels: ✨feat

#272 chore: Configure AWS SDK
  backend/demo/build.gradle
  frontend/src/features/search/pages/SearchPage.tsx
Labels: ⚙️chore

#274 fix: Resolve infinite rerender caused by useEffect dependency array
  frontend/src/features/main/hooks/useMainProducts.ts
  frontend/src/features/search/hooks/useSearchRanking.ts
  frontend/src/features/search/pages/SearchPage.tsx
  frontend/src/hooks/useProductImageUrls.ts
Labels: 🌈fix

#279 feat: product image upload
  backend/demo/build.gradle
  backend/demo/src/main/java/com/sesac/solbid/controller/AuctionController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UploadController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/AuctionEvent.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Product.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auction/request/AuctionCreateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auction/response/AuctionCreateResponse.java
  backend/demo/src/main/java/com/sesac/solbid/exception/CustomException.java
  backend/demo/src/main/java/com/sesac/solbid/exception/ErrorCode.java
  backend/demo/src/main/java/com/sesac/solbid/mapper/ProductMapper.java
  backend/demo/src/main/java/com/sesac/solbid/repository/AuctionEventRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductService.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/S3PresignServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/auction/AuctionService.java
  backend/demo/src/main/java/com/sesac/solbid/service/auction/AuctionServiceImpl.java
  frontend/src/features/auction/services/auctions.ts
  frontend/src/features/auction/types/auction.ts
  frontend/src/features/product/components/ImageGridUploader.tsx
  frontend/src/features/product/hooks/useProductSearch.ts
  frontend/src/features/product/hooks/useUpload.ts
  frontend/src/features/product/pages/NewAuctionProductPage.tsx
  frontend/src/features/product/services/products.ts
  frontend/src/features/product/services/uploads.ts
  frontend/src/features/product/types/product.ts
  frontend/src/features/upload/hooks/useUpload.ts
  frontend/src/features/upload/services/uploads.ts
  frontend/src/features/upload/types/upload.ts
  frontend/src/features/upload/utils/naming.ts
  frontend/src/utils/http.ts
Labels: ✨feat

#283 refactor: Limit recent search history to 10 items
  frontend/src/features/main/components/mockData.ts
  frontend/src/features/search/pages/SearchPage.tsx
  frontend/src/hooks/useProductImageUrls.ts
Labels: 🍀refactor

#289 feat: JWT 인증 적용 및 Javadoc 주석 추가
  backend/demo/src/main/java/com/sesac/solbid/controller/AuctionController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentRecordQueryController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PointController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PortOneController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductFinalizeController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UploadController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/payment/request/PaymentRecordSearchRequest.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentRecordQueryService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentRecordQueryServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PointService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PointServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/PortOneService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PortOneServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductService.java
  backend/demo/src/main/java/com/sesac/solbid/service/ProductServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/S3PresignServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/S3Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/S3StorageServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/UploadService.java
  backend/demo/src/main/java/com/sesac/solbid/service/UploadServiceImpl.java
  frontend/src/features/auction/services/auctions.ts
  frontend/src/features/auction/types/auction.ts
  frontend/src/features/payment/hooks/useServerPayments.ts
  frontend/src/features/payment/pages/PaymentRecordsPage.tsx
  frontend/src/features/payment/services/paymentService.ts
  frontend/src/features/payment/types/payment.ts
  frontend/src/features/product/pages/NewAuctionProductPage.tsx
  frontend/src/features/product/services/products.ts
  frontend/src/features/product/types/product.ts
  frontend/src/features/profile/api/point.ts
  frontend/src/features/profile/types/point.ts
  frontend/src/features/upload/services/uploads.ts
  frontend/src/features/upload/types/upload.ts
  frontend/src/utils/http.ts
Labels: ✨feat

#291 refactor: 서비스 레이어 도메인별 구조화
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentRecordQueryController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PointController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/PortOneController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductFinalizeController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/ProductRegisterController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UploadController.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PaymentRecordQueryService.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PaymentRecordQueryServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PaymentService.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PaymentServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PortOneService.java
  backend/demo/src/main/java/com/sesac/solbid/service/payment/PortOneServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/point/PointService.java
  backend/demo/src/main/java/com/sesac/solbid/service/point/PointServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/product/ProductImageService.java
  backend/demo/src/main/java/com/sesac/solbid/service/product/ProductService.java
  backend/demo/src/main/java/com/sesac/solbid/service/product/ProductServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/s3/S3PresignServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/s3/S3Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/s3/S3StorageService.java
  backend/demo/src/main/java/com/sesac/solbid/service/s3/S3StorageServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/upload/UploadService.java
  backend/demo/src/main/java/com/sesac/solbid/upload/UploadServiceImpl.java
Labels: 🍀refactor

#298 chore: Remove unused files
  backend/demo/src/main/java/com/sesac/solbid/advice/GloberAdvice.java
  backend/demo/src/main/java/com/sesac/solbid/controller/TestController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/TestDto.java
  backend/demo/src/main/java/com/sesac/solbid/repository/TestRepository.java
Labels: ⚙️chore

#304 feat: 경매 상품 상세 조회 api 및 화면 구현, 파일 서빙 기능 추가
  backend/demo/src/main/java/com/sesac/solbid/controller/AuctionQueryController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/FileController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Notification.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auction/response/AuctionDetailResponse.java
  backend/demo/src/main/java/com/sesac/solbid/repository/AuctionEventRepository.java
  backend/demo/src/main/java/com/sesac/solbid/repository/ProductImageRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/auction/AuctionQueryService.java
  backend/demo/src/main/java/com/sesac/solbid/service/auction/AuctionQueryServiceImpl.java
  frontend/src/features/auction/hooks/useAuctionDetail.ts
  frontend/src/features/auction/pages/AuctionDetailPage.tsx
  frontend/src/features/auction/services/auctions.ts
  frontend/src/features/auction/types/auctionDetail.ts
  frontend/src/router.tsx
  frontend/src/utils/toImageUrl.ts
Labels: ✨feat

#308 refactor: auth 및 user 패키지 DTO를 Java Record로 전환
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/EmailVerificationController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/CallbackRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetConfirmRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetOtpVerifyRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetVerifyRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/ResendOtpRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/ResendVerificationRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/VerifyCodeRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/AuthUrlResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/LoginSuccessResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/LoginRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/NicknameUpdateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/SignupRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/LoginResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/NicknameAvailabilityResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/SignupResponse.java
  backend/demo/src/main/java/com/sesac/solbid/service/auth/OAuth2Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/UserService.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/EmailVerificationControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/RecordDtoRestEndpointCompatibilityTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/UserControllerValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/request/AuthRequestValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/request/PasswordResetDtoTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/AuthUrlResponseSimpleTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/AuthUrlResponseTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponseJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponseSimpleTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponseTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/LoginSuccessResponseJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/auth/response/LoginSuccessResponseTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/LoginRequestJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/NicknameUpdateRequestJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/SignupRequestJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/UserRequestValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/response/LoginResponseJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/response/SignupResponseJsonTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/ApiContractVerificationTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/CompleteApiContractIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/OAuth2EndToEndIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/RecordDtoIntegrationCompatibilityTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/RecordDtoServiceCompatibilityTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/UserServiceSignupTest.java
  backend/demo/src/test/java/com/sesac/solbid/validation/RecordValidationIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/validation/SimpleRecordValidationTest.java
Labels: 🍀refactor

#309 feat(profile): 프로필 상단 영역에 사용자 온도 표시 기능 추가
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/test/java/com/sesac/solbid/integration/ApiContractVerificationTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/CompleteApiContractIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/OAuth2EndToEndIntegrationTest.java
  frontend/src/features/profile/api/profile.ts
  frontend/src/features/profile/components/ProfileStats.tsx
  frontend/src/features/profile/components/TemperatureCard.tsx
  frontend/src/features/profile/components/index.ts
  frontend/src/features/profile/components/mockData.ts
  frontend/src/features/profile/types/ProfileStatProps.ts
  frontend/src/features/profile/types/TemperatureCardProps.ts
  frontend/src/features/user/types/AuthTypes.ts
Labels: ✨feat

#322 feat(frontend): Order detail API integration
  frontend/src/features/order/components/detail/OrderDetailShipping.tsx
  frontend/src/features/order/components/detail/OrderDetailSummary.tsx
  frontend/src/features/order/components/mockData.ts
  frontend/src/features/order/hooks/useOrders.ts
  frontend/src/features/order/pages/OrderDetailPage.tsx
  frontend/src/features/order/services/OrderService.ts
  frontend/src/features/order/types/Order.ts
  frontend/src/features/order/types/OrderShipping.ts
  frontend/src/features/order/types/OrderSummary.ts
Labels: ✨feat

#329 docs(auth, user): 유저 및 인증 관련 클래스 JavaDoc 보강
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthTokenController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/EmailVerificationController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/SocialLogin.java
  backend/demo/src/main/java/com/sesac/solbid/domain/User.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/CallbackRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetConfirmRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetOtpVerifyRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/PasswordResetVerifyRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/ResendOtpRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/ResendVerificationRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/VerifyCodeRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/AuthUrlResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/EmailVerificationResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/LoginSuccessResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/LoginRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/NicknameUpdateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/SignupRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/LoginResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/NicknameAvailabilityResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/SignupResponse.java
Labels: 📄docs

#341 feat(user): 사용자 프로필 관리 및 보안 기능 강화
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/User.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/PasswordChangeRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/ProfileUpdateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/SensitiveProfileUpdateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/SignupRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/LoginResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/PasswordChangeResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/ProfileUpdateResponse.java
  backend/demo/src/main/java/com/sesac/solbid/exception/ErrorCode.java
  backend/demo/src/main/java/com/sesac/solbid/repository/UserRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/user/UserService.java
  backend/demo/src/test/java/com/sesac/solbid/controller/UserControllerProfileUpdateTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/UserControllerSecurityTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/ProfileUpdateRequestValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/PasswordChangeRequestValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/dto/user/request/SensitiveProfileUpdateRequestValidationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/UserServiceProfileUpdateTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/user/UserServiceSecurityTest.java
  frontend/package-lock.json
  frontend/package.json
  frontend/src/features/profile/components/EmailChangeModal.tsx
  frontend/src/features/profile/components/PasswordChangeModal.tsx
  frontend/src/features/profile/components/PasswordStrengthIndicator.tsx
  frontend/src/features/profile/components/ProfileEditModal.tsx
  frontend/src/features/profile/components/ProfileMenu.tsx
  frontend/src/features/profile/components/ProfileUser.tsx
  frontend/src/features/profile/components/SecurityConfirmDialog.tsx
  frontend/src/features/profile/components/SensitiveProfileEditModal.tsx
  frontend/src/features/profile/components/index.ts
  frontend/src/features/profile/components/mockData.ts
  frontend/src/features/profile/pages/ProfilePage.tsx
  frontend/src/features/profile/services/ProfileUpdateService.ts
  frontend/src/features/profile/services/index.ts
  frontend/src/features/profile/types/ProfileUpdateTypes.ts
  frontend/src/features/profile/types/index.ts
  frontend/src/features/profile/types/point.ts
  frontend/src/features/user/hooks/UseSignup.ts
  frontend/src/features/user/pages/Signup.tsx
  frontend/src/features/user/types/AuthTypes.ts
Labels: ✨feat

#346 fix: resolve type inference error in BidServiceImpl
  backend/demo/src/main/java/com/sesac/solbid/service/bid/BidServiceImpl.java
Labels: 🌈fix

#355 feat: Improve Product API performance
  backend/demo/src/main/java/com/sesac/solbid/repository/ProductRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/product/ProductServiceImpl.java
Labels: ✨feat

#358 refactor(backend): Organize Cart directory structure
  backend/demo/src/main/java/com/sesac/solbid/repository/cart/CartRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/cart/CartConverter.java
  backend/demo/src/main/java/com/sesac/solbid/service/cart/CartService.java
  backend/demo/src/main/java/com/sesac/solbid/service/cart/CartServiceImpl.java
Labels: 🍀refactor

#359 refactor(backend): Organize Wish directory structure
  backend/demo/src/main/java/com/sesac/solbid/controller/wish/WishController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/wish/request/WishRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/wish/response/WishActionResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/wish/response/WishResponse.java
  backend/demo/src/main/java/com/sesac/solbid/service/wish/WishService.java
  backend/demo/src/main/java/com/sesac/solbid/service/wish/WishServiceImpl.java
Labels: 🍀refactor

#370 feat: 경매 카드 실시간 타이머와 입찰 흐름 안정화
  backend/demo/src/main/java/com/sesac/solbid/controller/AuctionEventQueryController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auction/response/AuctionEventCardResponse.java
  backend/demo/src/main/java/com/sesac/solbid/repository/AuctionEventCardRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/auction/AuctionEventCardService.java
  frontend/src/features/auction/components/AuctionItem.tsx
  frontend/src/features/auction/components/AuctionList.tsx
  frontend/src/features/auction/hooks/useAuctionEventCards.ts
  frontend/src/features/auction/pages/AuctionDetailPage.tsx
  frontend/src/features/auction/pages/AuctionPage.tsx
  frontend/src/features/auction/services/auctionEvents.ts
  frontend/src/features/auction/services/auctions.ts
  frontend/src/features/auction/types/AuctionEventCard.ts
  frontend/src/features/auction/types/AuctionItemProps.ts
  frontend/src/features/auction/types/AuctionListProps.ts
Labels: ✨feat

#379 refactor: 위시리스트 중복 오류 해결 및 복합키 제약으로 중복 찜 허용
  backend/demo/src/main/java/com/sesac/solbid/domain/Wish.java
  backend/demo/src/main/java/com/sesac/solbid/security/SecurityConfig.java
  backend/demo/src/main/java/com/sesac/solbid/service/wish/WishServiceImpl.java
  frontend/src/features/auction/components/AuctionItem.tsx
  frontend/src/features/auction/components/AuctionList.tsx
  frontend/src/features/auction/pages/AuctionDetailPage.tsx
  frontend/src/features/auction/pages/AuctionPage.tsx
  frontend/src/features/auction/types/AuctionItemProps.ts
  frontend/src/features/auction/types/AuctionListProps.ts
  frontend/src/features/wish/hooks/useWishes.ts
Labels: 🍀refactor

#381 docs(docker): Docker 환경 설정 및 사용법 문서 오류 수정 (#380)
  docker-compose.dev.yml
  docker-compose.prod.yml
  scripts/check-ports.bat
  scripts/check-ports.sh
  scripts/deploy-prod.bat
  scripts/deploy-prod.sh
  scripts/dev-start-smart.bat
  scripts/dev-start-smart.sh
  scripts/docker-cleanup.bat
  scripts/docker-cleanup.sh
  scripts/docker-health-check.bat
  scripts/docker-health-check.sh
  scripts/docker-setup.bat
  scripts/docker-setup.sh
  scripts/docker-system-test.bat
  scripts/docker-system-test.sh
  scripts/healthcheck/wait-for-it.sh
  scripts/test-oauth-docker.bat
  scripts/test-oauth-docker.sh
  scripts/validate-env.bat
  scripts/validate-env.sh
  scripts/validate-setup.bat
  scripts/validate-setup.sh
Labels: 📄docs
