Repository porcupine7021/Solebid, pull requests merged in 2025-08, with the labels that each got.

#33 chore: Setup project directories
  frontend/src/components/.gitkeep
  frontend/src/constants/.gitkeep
  frontend/src/features/main/hooks/.gitkeep
  frontend/src/features/main/services/.gitkeep
  frontend/src/features/main/types/.gitkeep
  frontend/src/features/product/hooks/.gitkeep
  frontend/src/features/product/services/.gitkeep
  frontend/src/features/product/types/.gitkeep
  frontend/src/features/user/components/.gitkeep
  frontend/src/features/user/hooks/.gitkeep
  frontend/src/features/user/services/.gitkeep
  frontend/src/features/user/types/.gitkeep
  frontend/src/hooks/.gitkeep
  frontend/src/types/.gitkeep
  frontend/src/utils/.gitkeep
  frontend/tests/.gitkeep
Labels: ⚙️config

#34 feat: Add script for automated folder creation
  frontend/package.json
  frontend/scripts/create_feature.sh
Labels: ✨feat

#37 feat: OAuth2를 이용한 소셜 로그인 기능 구현
  backend/demo/build.gradle
  backend/demo/src/main/java/com/sesac/solbid/auth/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/config/SchedulerConfig.java
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/SocialLogin.java
  backend/demo/src/main/java/com/sesac/solbid/domain/User.java
  backend/demo/src/main/java/com/sesac/solbid/dto/ApiResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/OAuth2Dto.java
  backend/demo/src/main/java/com/sesac/solbid/dto/UserDto.java
  backend/demo/src/main/java/com/sesac/solbid/exception/ErrorCode.java
  backend/demo/src/main/java/com/sesac/solbid/exception/GlobalExceptionHandler.java
  backend/demo/src/main/java/com/sesac/solbid/exception/OAuth2Exception.java
  backend/demo/src/main/java/com/sesac/solbid/exception/OAuth2StateException.java
  backend/demo/src/main/java/com/sesac/solbid/repository/SocialLoginRepository.java
  backend/demo/src/main/java/com/sesac/solbid/security/SecurityConfig.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2StateService.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2UrlGenerator.java
  backend/demo/src/main/java/com/sesac/solbid/service/UserService.java
  backend/demo/src/test/java/com/sesac/solbid/DemoApplicationTests.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/OAuth2EndToEndIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServicePrivateMethodTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2StateServiceTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/UserServiceSocialLoginTest.java
  frontend/package-lock.json
  frontend/src/features/main/components/MainHeader.tsx
  frontend/src/features/user/pages/Login.tsx
  frontend/src/features/user/pages/NicknameSetup.tsx
  frontend/src/features/user/pages/OAuth2Callback.tsx
  frontend/src/router.tsx
Labels: ✨feat

#38 feat: Add Modal component
  frontend/src/components/.gitkeep
  frontend/src/components/Modal.tsx
  frontend/src/types/.gitkeep
  frontend/src/types/ModalProps.ts
Labels: ✨feat

#39 feat: Add Profile page
  frontend/src/features/profile/components/ProfileAccount.tsx
  frontend/src/features/profile/components/ProfileHeader.tsx
  frontend/src/features/profile/components/ProfileInfo.tsx
  frontend/src/features/profile/components/ProfileMenu.tsx
  frontend/src/features/profile/components/ProfileOrder.tsx
  frontend/src/features/profile/components/ProfilePoint.tsx
  frontend/src/features/profile/components/ProfileStats.tsx
  frontend/src/features/profile/components/ProfileUser.tsx
  frontend/src/features/profile/components/ProfileWish.tsx
  frontend/src/features/profile/components/index.ts
  frontend/src/features/profile/pages/ProfilePage.tsx
  frontend/src/features/profile/types/Order.ts
  frontend/src/features/profile/types/Stat.ts
  frontend/src/features/profile/types/Wish.ts
  frontend/src/router.tsx
Labels: ✨feat

#53 fix: AuthControllerTest의 로그아웃 API 엔드포인트 수정
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerTest.java
Labels: 🌈bugfix

#57 feat: Add a back button to Wish page
  frontend/src/features/product/components/wish/WishHeader.tsx
Labels: ✨feat

#66 feat: Add Cart page
  frontend/src/components/Button.tsx
  frontend/src/features/cart/components/CartEmptyList.tsx
  frontend/src/features/cart/components/CartHeader.tsx
  frontend/src/features/cart/components/CartItem.tsx
  frontend/src/features/cart/components/CartList.tsx
  frontend/src/features/cart/components/CartSummary.tsx
  frontend/src/features/cart/components/index.ts
  frontend/src/features/cart/components/mockData.ts
  frontend/src/features/cart/hooks/.gitkeep
  frontend/src/features/cart/pages/CartPage.tsx
  frontend/src/features/cart/services/.gitkeep
  frontend/src/features/cart/types/Cart.ts
  frontend/src/features/cart/types/CartHeaderProps.ts
  frontend/src/features/cart/types/CartItemProps.ts
  frontend/src/features/cart/types/CartListProps.ts
  frontend/src/features/cart/types/CartSummaryProps.ts
  frontend/src/router.tsx
  frontend/src/types/ButtonProps.ts
  frontend/src/utils/get-format-price.ts
Labels: ✨feat

#68 chore: Remove unused code related to Wish page
  frontend/src/features/product/components/wish/WishItem.tsx
  frontend/src/features/product/components/wish/WishList.tsx
Labels: ⚙️chore

#70 chore: dev 브랜치 PR 병합 시 이슈 자동 닫기 워크플로우 추가
  .github/workflows/auto-close-issue.yml
Labels: ⚙️chore

#72 fix: 이슈 자동 닫기 워크플로우의 잘못된 파라미터 수정
  .github/workflows/auto-close-issue.yml
Labels: 🌈fix

#74 feat: auto-close-issue 워크플로우 파일 제거
  .github/workflows/auto-close-issue.yml
Labels: ✨feat

#75 feat: payments charge UI 연결 및 PortOne 플로우 뼈대 추가
  frontend/src/features/payment/components/AdditionalInfo.tsx
  frontend/src/features/payment/components/AmountSelector.tsx
  frontend/src/features/payment/components/InfoBanner.tsx
  frontend/src/features/payment/components/PaymentMethodList.tsx
  frontend/src/features/payment/components/SecurityInfo.tsx
  frontend/src/features/payment/components/SummaryCard.tsx
  frontend/src/features/payment/constants/paymentOptions.ts
  frontend/src/features/payment/constants/portone.ts
  frontend/src/features/payment/constants/presets.ts
  frontend/src/features/payment/pages/ChargePointsPage.tsx
  frontend/src/features/payment/pages/ChargeResultPage.tsx
  frontend/src/features/payment/services/portoneService.ts
  frontend/src/features/payment/types/index.ts
  frontend/src/router.tsx
Labels: ✨feat

#80 refactor: Extract components related to Auction page
  frontend/src/features/product/components/Auction.tsx
  frontend/src/features/product/components/auction/AuctionHeader.tsx
  frontend/src/features/product/components/auction/AuctionItem.tsx
  frontend/src/features/product/components/auction/AuctionList.tsx
  frontend/src/features/product/components/auction/AuctionModal.tsx
  frontend/src/features/product/components/auction/AuctionSearch.tsx
  frontend/src/features/product/components/auction/index.ts
  frontend/src/features/product/components/auction/mockData.ts
  frontend/src/features/product/components/index.ts
  frontend/src/features/product/pages/AuctionPage.tsx
  frontend/src/features/product/types/auction/AuctionItem.ts
  frontend/src/features/product/types/auction/AuctionItemProps.ts
  frontend/src/features/product/types/auction/AuctionListProps.ts
  frontend/src/features/product/types/auction/AuctionModalProps.ts
  frontend/src/features/product/types/auction/AuctionSearchProps.ts
Labels: 🍀refactor

#81 refactor: Extract components related to Brand page
  frontend/src/features/product/components/Brand.tsx
  frontend/src/features/product/components/brand/BrandHeader.tsx
  frontend/src/features/product/components/brand/BrandItem.tsx
  frontend/src/features/product/components/brand/BrandList.tsx
  frontend/src/features/product/components/brand/BrandModal.tsx
  frontend/src/features/product/components/brand/BrandPopular.tsx
  frontend/src/features/product/components/brand/index.ts
  frontend/src/features/product/components/brand/mockData.ts
  frontend/src/features/product/components/index.ts
  frontend/src/features/product/pages/BrandPage.tsx
  frontend/src/features/product/types/brand/Brand.ts
  frontend/src/features/product/types/brand/BrandItemProps.ts
  frontend/src/features/product/types/brand/BrandListProps.ts
  frontend/src/features/product/types/brand/BrandModalProps.ts
  frontend/src/features/product/types/brand/BrandPopular.ts
Labels: 🍀refactor

#84 refactor: Extract components related to Category page
  frontend/src/features/product/components/Category.tsx
  frontend/src/features/product/components/category/CategoryBreadcrumb.tsx
  frontend/src/features/product/components/category/CategoryHeader.tsx
  frontend/src/features/product/components/category/CategoryItem.tsx
  frontend/src/features/product/components/category/CategoryList.tsx
  frontend/src/features/product/components/category/CategorySearch.tsx
  frontend/src/features/product/components/category/index.ts
  frontend/src/features/product/components/category/mockData.ts
  frontend/src/features/product/components/index.ts
  frontend/src/features/product/pages/CategoryPage.tsx
  frontend/src/features/product/types/category/Category.ts
  frontend/src/features/product/types/category/CategoryBreadcrumb.ts
  frontend/src/features/product/types/category/CategoryHeaderProps.ts
  frontend/src/features/product/types/category/CategoryItemProps.ts
  frontend/src/features/product/types/category/CategoryListProps.ts
  frontend/src/features/product/types/category/CategoryOption.ts
  frontend/src/features/product/types/category/CategorySearchProps.ts
Labels: 🍀refactor

#86 fix : payment-point-entity-types-mismatch(build 형식 수정)
  backend/demo/src/main/java/com/sesac/solbid/domain/Payments.java
  backend/demo/src/main/java/com/sesac/solbid/domain/PointTransaction.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentServiceImpl.java
Labels: 🌈fix

#92 refactor: Remove React.FC from components
  frontend/src/components/BackPress.tsx
  frontend/src/components/Button.tsx
  frontend/src/components/Modal.tsx
  frontend/src/components/Pagination.tsx
  frontend/src/components/Toast.tsx
  frontend/src/features/cart/components/CartItem.tsx
  frontend/src/features/cart/components/CartList.tsx
  frontend/src/features/cart/components/CartSummary.tsx
  frontend/src/features/product/components/auction/AuctionItem.tsx
  frontend/src/features/product/components/auction/AuctionList.tsx
  frontend/src/features/product/components/auction/AuctionModal.tsx
  frontend/src/features/product/components/auction/AuctionSearch.tsx
  frontend/src/features/product/components/brand/BrandItem.tsx
  frontend/src/features/product/components/brand/BrandList.tsx
  frontend/src/features/product/components/brand/BrandModal.tsx
  frontend/src/features/product/components/brand/BrandPopular.tsx
  frontend/src/features/product/components/category/CategoryBreadcrumb.tsx
  frontend/src/features/product/components/category/CategoryHeader.tsx
  frontend/src/features/product/components/category/CategoryItem.tsx
  frontend/src/features/product/components/category/CategoryList.tsx
  frontend/src/features/product/components/category/CategorySearch.tsx
  frontend/src/features/product/components/ranking/RankingBidderItem.tsx
  frontend/src/features/product/components/ranking/RankingBidderList.tsx
  frontend/src/features/product/components/ranking/RankingProductItem.tsx
  frontend/src/features/product/components/ranking/RankingProductList.tsx
  frontend/src/features/product/components/ranking/RankingSellerItem.tsx
  frontend/src/features/product/components/ranking/RankingSellerList.tsx
  frontend/src/features/product/components/ranking/RankingTab.tsx
  frontend/src/features/product/components/search/SearchHeader.tsx
  frontend/src/features/product/components/search/SearchItem.tsx
  frontend/src/features/product/components/search/SearchSidebar.tsx
  frontend/src/features/product/types/brand/BrandModalProps.ts
  frontend/src/features/profile/components/ProfileBid.tsx
  frontend/src/features/profile/components/ProfileStats.tsx
  frontend/src/features/profile/components/ProfileWish.tsx
  frontend/src/features/wish/components/WishItem.tsx
  frontend/src/features/wish/components/WishList.tsx
  frontend/src/features/wish/components/WishSearch.tsx
Labels: 🍀refactor

#94 feat: Apply font for improved readability
  frontend/public/fonts/Pretendard-Regular.woff
  frontend/public/fonts/Pretendard-Regular.woff2
  frontend/src/index.css
  frontend/tailwind.config.js
Labels: ✨feat

#103 feat: 결제 페이지 api 연결 및 user 포인트 증감 로직 구현 (JPQL update)
  backend/demo/src/main/java/com/sesac/solbid/controller/PaymentController.java
  backend/demo/src/main/java/com/sesac/solbid/domain/Payments.java
  backend/demo/src/main/java/com/sesac/solbid/dto/response/PortOnePaymentResponse.java
  backend/demo/src/main/java/com/sesac/solbid/repository/UserRepository.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentService.java
  backend/demo/src/main/java/com/sesac/solbid/service/PaymentServiceImpl.java
  backend/demo/src/main/java/com/sesac/solbid/service/PortOneService.java
  frontend/index.html
  frontend/src/features/payment/components/PaymentMethodList.tsx
  frontend/src/features/payment/components/PortoneTestButton.tsx
  frontend/src/features/payment/constants/portone.ts
  frontend/src/features/payment/pages/ChargePointsPage.tsx
  frontend/src/features/payment/services/portoneService.ts
  frontend/src/features/payment/types/portone-global.d.ts
Labels: ✨feat

#114 feat: 메인 페이지 결제 내역 조회 기능 추가, 포인트 섹션 UI 수정
  frontend/src/features/profile/components/ProfilePoint.tsx
  frontend/src/features/profile/components/mockData.ts
Labels: ✨feat

#119 refactor: Cleanup Bid page
  frontend/src/features/product/pages/BidPage.tsx
Labels: 🍀refactor

#120 refactor: Cleanup Search page
  frontend/src/features/product/components/search/mockData.ts
  frontend/src/features/product/pages/SearchPage.tsx
  frontend/src/features/product/types/search/Search.ts
Labels: 🍀refactor

#122 refactor: Cleanup Brand page
  frontend/src/features/product/components/brand/BrandModal.tsx
  frontend/src/features/product/types/brand/BrandModalProps.ts
Labels: 🍀refactor

#124 fix: Correct pagination UI
  frontend/src/features/order/pages/OrderPage.tsx
  frontend/src/features/product/pages/CategoryPage.tsx
  frontend/src/features/wish/pages/WishPage.tsx
Labels: 🌈fix

#127 feat: Add declarative modal
  frontend/src/App.tsx
  frontend/src/contexts/modal/ModalContext.tsx
  frontend/src/contexts/modal/modal.ts
  frontend/src/features/profile/components/ProfilePoint.tsx
Labels: ✨feat

#129 feat: Add declarative Toast
  frontend/src/App.tsx
  frontend/src/contexts/toast/ToastContext.tsx
  frontend/src/contexts/toast/toast.ts
  frontend/src/features/product/pages/BidPage.tsx
  frontend/src/features/wish/components/WishItem.tsx
  frontend/src/features/wish/components/WishList.tsx
  frontend/src/features/wish/pages/WishPage.tsx
  frontend/src/features/wish/types/WishItemProps.ts
Labels: ✨feat

#131 refactor: Remove unnecessary button component
  frontend/src/components/Button.tsx
  frontend/src/features/cart/pages/CartPage.tsx
Labels: 🍀refactor

#135 feat: Add Policy page
  frontend/src/assets/privacy-policy.md
  frontend/src/features/policy/pages/PolicyPage.tsx
  frontend/src/features/profile/components/ProfileAccount.tsx
  frontend/src/index.css
  frontend/src/router.tsx
Labels: ✨feat

#146 feat: 사용자 인증/회원가입 모듈화
  frontend/src/features/user/components/.gitkeep
  frontend/src/features/user/components/SocialLoginButtons.tsx
  frontend/src/features/user/components/TermsModal.tsx
  frontend/src/features/user/hooks/.gitkeep
  frontend/src/features/user/hooks/UseEmailLogin.ts
  frontend/src/features/user/hooks/UseNicknameSetup.ts
  frontend/src/features/user/hooks/UseOAuth2Callback.ts
  frontend/src/features/user/hooks/UseSignup.ts
  frontend/src/features/user/pages/Login.tsx
  frontend/src/features/user/pages/NicknameSetup.tsx
  frontend/src/features/user/pages/OAuth2Callback.tsx
  frontend/src/features/user/pages/Signup.tsx
  frontend/src/features/user/services/.gitkeep
  frontend/src/features/user/services/AuthService.ts
  frontend/src/features/user/services/UserService.ts
  frontend/src/features/user/types/.gitkeep
  frontend/src/features/user/types/AuthTypes.ts
  frontend/src/features/user/types/SignupTypes.ts
Labels: ✨feat

#150 refactor: Auth DTO 요청/응답 DTO 분리
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/OAuth2Dto.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/request/CallbackRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/AuthUrlResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/auth/response/LoginSuccessResponse.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2Service.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthTokenControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/integration/OAuth2EndToEndIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceTest.java
Labels: 🍀refactor

#151 feat: Add Setting page
  frontend/src/features/profile/components/mockData.ts
  frontend/src/features/setting/components/SettingAccount.tsx
  frontend/src/features/setting/components/SettingLanguage.tsx
  frontend/src/features/setting/components/SettingNav.tsx
  frontend/src/features/setting/components/SettingNotification.tsx
  frontend/src/features/setting/components/SettingPayment.tsx
  frontend/src/features/setting/components/SettingProfile.tsx
  frontend/src/features/setting/components/SettingSecurity.tsx
  frontend/src/features/setting/components/SettingSidebar.tsx
  frontend/src/features/setting/components/SettingTheme.tsx
  frontend/src/features/setting/components/index.ts
  frontend/src/features/setting/components/mockData.ts
  frontend/src/features/setting/pages/SettingPage.tsx
  frontend/src/features/setting/types/SettingLanguage.ts
  frontend/src/features/setting/types/SettingNavProps.ts
  frontend/src/features/setting/types/SettingNotificationProps.ts
  frontend/src/features/setting/types/SettingPrivacyProps.ts
  frontend/src/features/setting/types/SettingSecurityProps.ts
  frontend/src/features/setting/types/SettingSidebarProps.ts
  frontend/src/features/setting/types/SettingTab.ts
  frontend/src/features/setting/types/SettingTheme.ts
  frontend/src/router.tsx
Labels: ✨feat

#152 refactor: User DTO 요청/응답 DTO 분리
  backend/demo/src/main/java/com/sesac/solbid/controller/AuthController.java
  backend/demo/src/main/java/com/sesac/solbid/controller/UserController.java
  backend/demo/src/main/java/com/sesac/solbid/dto/UserDto.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/LoginRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/NicknameUpdateRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/request/SignupRequest.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/LoginResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/NicknameAvailabilityResponse.java
  backend/demo/src/main/java/com/sesac/solbid/dto/user/response/SignupResponse.java
  backend/demo/src/main/java/com/sesac/solbid/service/OAuth2Service.java
  backend/demo/src/main/java/com/sesac/solbid/service/UserService.java
  backend/demo/src/test/java/com/sesac/solbid/controller/AuthControllerTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceIntegrationTest.java
  backend/demo/src/test/java/com/sesac/solbid/service/OAuth2ServiceTest.java
  backend/demo/src/test/resources/application-test.properties
Labels: 🍀refactor
